apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SEU_USUARIO/llm-portfolio.git
    targetRevision: main
    path: keda
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
