apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:sereno4/LLM-Pipeline-Platform-.git
    targetRevision: main
    path: redis-queue
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-queue
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
